#!/usr/bin/env bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Layer 02 - Local config (no AWS resources; only local files).
#   up   : read the CloudFormation stack outputs and write
#          deploy/state/outputs.env + frontend/.env (public identifiers only).
#   down : reset deploy/state/outputs.env to a clean stub and blank frontend/.env
#          back to placeholders.
set -euo pipefail
source "$(dirname "$0")/_lib.sh"
ACTION="${1:-up}"

config_up() {
  step "Layer 02 UP - Write local config from stack outputs"
  get_out() { aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text; }
  run_capture USER_POOL_ID        get_out UserPoolId
  run_capture USER_POOL_CLIENT_ID get_out UserPoolClientId
  run_capture IDENTITY_POOL_ID    get_out IdentityPoolId
  run_capture REGION              get_out Region
  [ -n "$USER_POOL_ID" ] && [ "$USER_POOL_ID" != "None" ] || die "no stack outputs - did ./01-foundation.sh up succeed?"
  ok "UserPoolId=$USER_POOL_ID ClientId=$USER_POOL_CLIENT_ID IdentityPoolId=$IDENTITY_POOL_ID Region=$REGION"

  info "Writing $STATE_FILE (for 03-registry.sh + teardown)"
  run mkdir -p "$STATE_DIR"
  # PRESERVE any ids written by later layers. Truncating them here would strand the
  # live registry / site resources: teardown reads these ids to find what to delete.
  CARRIED=""
  if [ -f "$STATE_FILE" ]; then
    CARRIED="$(grep -E '^(REGISTRY_(ARN|ID|AUTH_MODE)|SITE_(BUCKET|OAC_ID|DIST_ID|DOMAIN)|SAMPLE_(GW_ID|GW_URL|GW_TARGET_ID|OAUTH_PROVIDER_ARN|M2M_CLIENT_ID|COGNITO_DOMAIN|RECORD_ID))=' "$STATE_FILE" 2>/dev/null || true)"
  fi
  cat > "$STATE_FILE" <<EOF
# Generated by 02-config.sh from CloudFormation stack '$STACK_NAME'.
# Public identifiers only. Gitignored. REGISTRY_ID is written by 03-registry.sh up
# and the SITE_* ids by 05-site.sh up; 02-config.sh up carries them forward.
USER_POOL_ID=$USER_POOL_ID
USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID
PROVIDER=cognito-idp.$REGION.amazonaws.com/$USER_POOL_ID
IDENTITY_POOL_ID=$IDENTITY_POOL_ID
REGION=$REGION
EOF
  if [ -n "$CARRIED" ]; then
    printf '%s\n' "$CARRIED" >> "$STATE_FILE"
    ok "carried forward existing ids:"
    printf '%s\n' "$CARRIED" | sed 's/^/      /'
  fi
  ok "wrote $STATE_FILE"

  info "Writing $FRONTEND_ENV (VITE_REGISTRY_ID + VITE_REGISTRY_AUTH_MODE filled by 03-registry.sh up)"
  # Keep an existing VITE_REGISTRY_ID / auth mode so re-running this layer does not
  # point the SPA at nothing (or at the wrong auth model) while a registry is live.
  PREV_REG=""
  PREV_MODE=""
  PREV_PROVIDER=""
  PREV_SCOPES=""
  PREV_GW=""
  if [ -f "$FRONTEND_ENV" ]; then
    PREV_REG="$(grep -E '^VITE_REGISTRY_ID=' "$FRONTEND_ENV" 2>/dev/null | tail -1 | cut -d= -f2 || true)"
    PREV_MODE="$(grep -E '^VITE_REGISTRY_AUTH_MODE=' "$FRONTEND_ENV" 2>/dev/null | tail -1 | cut -d= -f2 || true)"
    PREV_PROVIDER="$(grep -E '^VITE_OAUTH_CREDENTIAL_PROVIDER_ARN=' "$FRONTEND_ENV" 2>/dev/null | tail -1 | cut -d= -f2 || true)"
    PREV_SCOPES="$(grep -E '^VITE_OAUTH_CREDENTIAL_PROVIDER_SCOPES=' "$FRONTEND_ENV" 2>/dev/null | tail -1 | cut -d= -f2 || true)"
    PREV_GW="$(grep -E '^VITE_SAMPLE_GATEWAY_URL=' "$FRONTEND_ENV" 2>/dev/null | tail -1 | cut -d= -f2 || true)"
  fi
  cat > "$FRONTEND_ENV" <<EOF
VITE_AWS_REGION=$REGION
VITE_USER_POOL_ID=$USER_POOL_ID
VITE_USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID
VITE_IDENTITY_POOL_ID=$IDENTITY_POOL_ID
VITE_REGISTRY_ID=$PREV_REG
VITE_REGISTRY_AUTH_MODE=${PREV_MODE:-CUSTOM_JWT}
VITE_OAUTH_CREDENTIAL_PROVIDER_ARN=$PREV_PROVIDER
VITE_OAUTH_CREDENTIAL_PROVIDER_SCOPES=$PREV_SCOPES
VITE_SAMPLE_GATEWAY_URL=$PREV_GW
EOF
  [ -n "$PREV_REG" ] && ok "kept VITE_REGISTRY_ID=$PREV_REG"
  [ -n "$PREV_MODE" ] && ok "kept VITE_REGISTRY_AUTH_MODE=$PREV_MODE"
  [ -n "$PREV_PROVIDER" ] && ok "kept VITE_OAUTH_CREDENTIAL_PROVIDER_ARN"
  ok "wrote $FRONTEND_ENV"
  step "Layer 02 UP complete"
  info "Next: ./03-registry.sh up"
}

config_down() {
  step "Layer 02 DOWN - Reset local config"
  printf '# Reset %s. Repopulated by 02-config.sh up on next deploy.\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$STATE_FILE"
  ok "reset $STATE_FILE"
  cat > "$FRONTEND_ENV" <<'EOF'
VITE_AWS_REGION=us-east-1
VITE_USER_POOL_ID=us-east-1_EXAMPLE
VITE_USER_POOL_CLIENT_ID=EXAMPLECLIENTID
VITE_IDENTITY_POOL_ID=us-east-1:00000000-0000-0000-0000-000000000000
VITE_REGISTRY_ID=
VITE_REGISTRY_AUTH_MODE=CUSTOM_JWT
VITE_OAUTH_CREDENTIAL_PROVIDER_ARN=
VITE_OAUTH_CREDENTIAL_PROVIDER_SCOPES=
VITE_SAMPLE_GATEWAY_URL=
EOF
  ok "reset $FRONTEND_ENV to placeholders"
  step "Layer 02 DOWN complete"
}

case "$ACTION" in
  up)   config_up ;;
  down) config_down ;;
  *)    die "usage: $0 up|down" ;;
esac
